
---
- name: Login, build and push the glpi_automation app image to dockerhub
  hosts: localhost


  tasks:
    - name: login to dockerhub 
      ansible.builtin.command:
        echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      ignore_errors: yes  

    - name: remove running container  
      ansible.builtin.command:
        docker rm -f glpi
      ignore_errors: yes  

    - name : remove used image of glpi  
      ansible.builtin.command:
        docker rmi ahmedmarzouki1993/glpi_automation
      ignore_errors: yes

    - name : build the image of glpi app from dockerfile using commit hash as a tag
      ansible.builtin.command:
         docker build -t ahmedmarzouki1993/glpi_automation:{{ ansible_env.GIT_COMMIT | regex_replace('^(.{8}).*$', '\\1') }} .
      ignore_errors: yes

    - name: push the new glpi  image to dockerhub
      ansible.builtin.command:
        docker push ahmedmarzouki1993/glpi_automation:{{ ansible_env.GIT_COMMIT | regex_replace('^(.{8}).*$', '\\1') }}
      ignore_errors: yes





