
---
- name: Login, build and push the glpi_automation app image to dockerhub
  hosts: localhost


  tasks:
    - name: login to dockerhub 
      ansible.builtin.command:
        echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      ignore_errors: yes  

    - name: remove running container  
      ansible.builtin.command:
        docker rm -f glpi
      ignore_errors: yes  

    - name : remove used image of glpi  
      ansible.builtin.command:
        docker images -q | grep 'ahmedmarzouki1993/glpi_automation' | xargs -I {} docker rmi {}
      ignore_errors: yes

    - name : build the image of glpi app from dockerfile
      ansible.builtin.command:
        docker build -t ahmedmarzouki1993/glpi_automation:${GIT_COMMIT.take(8)} .
      ignore_errors: yes

    - name: push the new glpi  image to dockerhub
      ansible.builtin.command:
        docker push ahmedmarzouki1993/glpi_automation:${GIT_COMMIT.take(8)}
      ignore_errors: yes





