
---
- name: Login, build and push the glpi_automation app image to dockerhub
  hosts: localhost


  tasks:
    - name: login to dockerhub 
      ansible.builtin.command:
        echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      ignore_errors: yes  

    - name: remove running container  
      ansible.builtin.command:
        docker rm -f glpi
      ignore_errors: yes  
 

    - name: Get image ID for the repository
      command: docker images -q ahmedmarzouki1993/glpi_automation
      register: image_id
      changed_when: false
      ignore_errors: yes

    - name: Remove the image
      command: docker rmi "{{ image_id.stdout_lines[0] }}"
      when: image_id.stdout_lines|length > 0

    - name : build the image of glpi app from dockerfile using commit hash as a tag
      ansible.builtin.command:
        docker build -t ahmedmarzouki1993/glpi_automation:{{ ansible_env.GIT_COMMIT[:8] }} .
      ignore_errors: yes

    - name: push the new glpi  image to dockerhub
      ansible.builtin.command:
        docker push ahmedmarzouki1993/glpi_automation:{{ ansible_env.GIT_COMMIT[:8] }}
      ignore_errors: yes
      
    - name: Configure Git User Email
      ansible.builtin.command: git config --global user.email "$GIT_CONFIG_EMAIL"
      ignore_errors: yes

    - name: Configure Git User Name
      ansible.builtin.command: git config --global user.name "$GIT_CONFIG_NAME"
      ignore_errors: yes







