
---
- name: Login, build and push the glpi_automation app image to dockerhub
  hosts: localhost


  tasks:
    - name: login to dockerhub 
      ansible.builtin.command:
        echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      ignore_errors: yes  

    - name: remove running container  
      ansible.builtin.command:
        docker rm -f glpi
      ignore_errors: yes  
 

    - name: Get image ID for the repository
      command: docker images -q ahmedmarzouki1993/glpi_automation
      register: image_id
      changed_when: false
      ignore_errors: yes

    - name: Remove the image
      command: docker rmi "{{ image_id.stdout_lines[0] }}"
      when: image_id.stdout_lines|length > 0

    - name : build the image of glpi app from dockerfile using commit hash as a tag
      ansible.builtin.command:
        docker build -t ahmedmarzouki1993/glpi_automation:{{ ansible_env.GIT_COMMIT[:8] }} .
      ignore_errors: yes

    - name: push the new glpi  image to dockerhub
      ansible.builtin.command:
        docker push ahmedmarzouki1993/glpi_automation:{{ ansible_env.GIT_COMMIT[:8] }}
      ignore_errors: yes


    - name: Set temporary HOME environment variable for cloning
      ansible.builtin.git:
        repo: https://ahmedmarzouki1993:${GH_TOKEN}@${CONFIG_REPO_URL}
        dest: /tmp/glpi_kubernetes
      environment:
        HOME: /tmp

    - name: Work on the cloned repository
      ansible.builtin.shell: |
        cd /tmp/glpi_kubernetes
        git config --global user.email "$GIT_CONFIG_EMAIL"
        git config --global user.name "$GIT_CONFIG_NAME"
        cd glpi-manifest-files
        sed -i 's/^ *image: ahmedmarzouki1993\/glpi_automation.*/          image: ahmedmarzouki1993\/glpi_automation:{{ ansible_env.GIT_COMMIT[:8] }}/' deployment_glpi.yml

        git add .
        git commit -am "change container build version to build {{ ansible_env.GIT_COMMIT[:8] }}/"
        git push
      environment:
        HOME: /tmp






